POST https://pilots.endorians.com:3333/blueprints/create
Content-Type: application/json

{
    "args": {
        "batchId": "my_batch_8",
        "jarPath": "s3://endor-public/pipeline.jar",
        "ethereumCustomerId": "5a2421f0e521347a7c7b92b8",
        "tokensCustomerId": "5a5e576dc78caa347f4a140c",
        "facadeHost": "localhost",
        "logicalDate": "2018-01-30",
        "ethereumToken": "cdM3rwOXgXdq1hafcbTWmnvAya1Sa6z4KHfbxy/r",
        "erc20Token": "bPVPDNbUn1WzOiPQcgkEhorksFN83XJC62OziXBA",
        "clusterSetName": "productionClusterSet"
    },
    "metadata": {
        "type": "integration-ethereum",
        "customer": "ethereum"
    },
    "jobs": {
        "moveLogsInboxToInProgress": {
            "jobType": "s3Move",
            "body": {
                "config": {
                    "newPrefix": "ethereum/logs/InProgress/${batchId}/",
                    "sourceBucket": "endor-blockchains",
                    "oldPrefix": "ethereum/logs/Inbox/",
                    "destinationBucket": "endor-blockchains"
                },
                "metadata": {
                    "sub_operation": "moveLogsToInbox",
                    "operation": "onboarding",
                    "customer": "ethereum"
                },
                "env": {
                    "s3": {},
                    "spark": {
                        "cluster_id": "",
                        "clusterKey": "spark.production"
                    },
                    "featureFlags": {
                        "io": "s3"
                    },
                    "envConfig": {
                        "s3": {}
                    }
                }
            }
        },
        "moveRatesInboxToInProgress": {
            "jobType": "s3Move",
            "body": {
                "config": {
                    "newPrefix": "ethereum/rates/InProgress/${batchId}/",
                    "sourceBucket": "endor-blockchains",
                    "oldPrefix": "ethereum/rates/Inbox/",
                    "destinationBucket": "endor-blockchains"
                },
                "metadata": {
                    "sub_operation": "moveRatesToInbox",
                    "operation": "onboarding",
                    "customer": "ethereum"
                },
                "env": {
                    "s3": {},
                    "spark": {
                        "cluster_id": "",
                        "clusterKey": "spark.production"
                    },
                    "featureFlags": {
                        "io": "s3"
                    },
                    "envConfig": {
                        "s3": {}
                    }
                }
            }
        },
        "moveBlocksInboxToInProgress": {
            "jobType": "s3Move",
            "body": {
                "config": {
                    "newPrefix": "ethereum/blocks/InProgress/${batchId}/",
                    "destinationBucket": "endor-blockchains",
                    "oldPrefix": "ethereum/blocks/Inbox/",
                    "sourceBucket": "endor-blockchains"
                },
                "metadata": {
                    "sub_operation": "moveBlocksToInProgress",
                    "operation": "onboarding",
                    "customer": "ethereum"
                },
                "env": {
                    "s3": {},
                    "spark": {
                        "cluster_id": "",
                        "clusterKey": "spark.production"
                    },
                    "featureFlags": {
                        "io": "s3"
                    },
                    "envConfig": {
                        "s3": {}
                    }
                }
            }
        },
        "fetchTokenRates": {
            "jobType": "emr_ethereumTokenRatesPipeline",
            "body": {
                "config":{
                    "metadataPath": "s3://endor-blockchains/ethereum/logs/metadata/",
                    "inputPath": "s3://endor-blockchains/ethereum/rates/InProgress/${batchId}/",
                    "output": "s3://source-erc20-tokens/ratesFacts/Inbox/"
                },
                "env": {
                    "spark": {
                        "additionalConfiguration": [],
                        "destinationEMRHost": "emr.${clusterSetName}-fast.endorians.com",
                        "destinationEMRQueue": "emr-${clusterSetName}-fast-tasks",
                        "jarPath": "${jarPath}",
                        "isPrimary": true
                    }
                }
            }
        },
        "parseEthereumTransactions": {
            "jobType": "emr_ethereumTransactionsPipeline",
            "body": {
                "config":{
                    "input": "s3://endor-blockchains/ethereum/blocks/InProgress/${batchId}/",
                    "output": "s3://source-ethereum/TransactionsNew/Inbox/"
                },
                "env": {
                    "spark": {
                        "additionalConfiguration": [
                            ["spark.files.maxPartitionBytes", "1"]
                        ],
                        "destinationEMRHost": "emr.${clusterSetName}-fast.endorians.com",
                        "destinationEMRQueue": "emr-${clusterSetName}-fast-tasks",
                        "jarPath": "${jarPath}",
                        "isPrimary": true
                    }
                }
            }
        },
        "onboardEthereumTransactions": {
            "jobType": "onboard",
            "body": {
                "facadeHost": "${facadeHost}",
                "customerId": "${ethereumCustomerId}",
                "dataschemeIds": ["5a65f51dc78caa347f4a395e"],
                "logicalDateTime": "${logicalDate}T00:00:00Z",
                "token": "Key ${ethereumToken}"
            }
        },
        "onboardEthereumTransactionsPolling": {
            "jobType": "endorTaskStatusPolling",
            "body": {
                "facadeHost": "${facadeHost}",
                "customerId": "${ethereumCustomerId}",
                "token": "Key ${ethereumToken}",
                "taskId": "${taskId}"
            }
        },
        "parseEthereumBlockHeaders": {
            "jobType": "emr_ethereumBlocksPipeline",
            "body": {
                "config":{
                    "input": "s3://endor-blockchains/ethereum/blocks/InProgress/${batchId}/",
                    "output": "s3://endor-blockchains/ethereum/blocks/headers/${batchId}/"
                },
                "env": {
                    "spark": {
                        "additionalConfiguration": [
                                                    ["spark.files.maxPartitionBytes", "1"]
                                                ],
                        "destinationEMRHost": "emr.${clusterSetName}-fast.endorians.com",
                        "destinationEMRQueue": "emr-${clusterSetName}-fast-tasks",
                        "jarPath": "${jarPath}",
                        "isPrimary": true
                    }
                }
            }
        },
        "parseEthereumTokenTransactions": {
            "jobType": "emr_ethereumTokensPipeline",
            "body": {
                "config":{
                    "input": "s3://endor-blockchains/ethereum/logs/InProgress/${batchId}/",
                    "blocksInput": "s3://endor-blockchains/ethereum/blocks/headers/${batchId}/",
                    "metadataCachePath": "s3://endor-blockchains/ethereum/logs/metadata/",
                    "metadataOutputPath": "s3://source-erc20-tokens/meta_meta/Inbox/",
                    "output": "s3://source-erc20-tokens/transactions/Inbox/"
                },
                "env": {
                    "spark": {
                        "additionalConfiguration": [],
                        "destinationEMRHost": "emr.${clusterSetName}-fast.endorians.com",
                        "destinationEMRQueue": "emr-${clusterSetName}-fast-tasks",
                        "jarPath": "${jarPath}",
                        "isPrimary": true
                    }
                }
            }
        },
        "moveBlocksInProgressToArchive": {
            "jobType": "s3Move",
            "body": {
                "config": {
                    "oldPrefix": "ethereum/blocks/InProgress/${batchId}/",
                    "sourceBucket": "endor-blockchains",
                    "newPrefix": "ethereum/blocks/Archive/${batchId}/",
                    "destinationBucket": "endor-blockchains"
                },
                "metadata": {
                    "sub_operation": "moveBlocksToArchive",
                    "operation": "onboarding",
                    "customer": "ethereum"
                },
                "env": {
                    "s3": {},
                    "spark": {
                        "cluster_id": "",
                        "clusterKey": "spark.production"
                    },
                    "featureFlags": {
                        "io": "s3"
                    },
                    "envConfig": {
                        "s3": {}
                    }
                }
            }
        },
        "moveLogsInProgressToArchive": {
            "jobType": "s3Move",
            "body": {
                "config": {
                    "oldPrefix": "ethereum/logs/InProgress/${batchId}/",
                    "sourceBucket": "endor-blockchains",
                    "newPrefix": "ethereum/logs/Archive/${batchId}/",
                    "destinationBucket": "endor-blockchains"
                },
                "metadata": {
                    "sub_operation": "moveLogsToArchive",
                    "operation": "onboarding",
                    "customer": "ethereum"
                },
                "env": {
                    "s3": {},
                    "spark": {
                        "cluster_id": "",
                        "clusterKey": "spark.production"
                    },
                    "featureFlags": {
                        "io": "s3"
                    },
                    "envConfig": {
                        "s3": {}
                    }
                }
            }
        },
        "moveRatesInProgressToArchive": {
            "jobType": "s3Move",
            "body": {
                "config": {
                    "oldPrefix": "ethereum/rates/InProgress/${batchId}/",
                    "sourceBucket": "endor-blockchains",
                    "newPrefix": "ethereum/rates/Archive/${batchId}/",
                    "destinationBucket": "endor-blockchains"
                },
                "metadata": {
                    "sub_operation": "moveRatesToArchive",
                    "operation": "onboarding",
                    "customer": "ethereum"
                },
                "env": {
                    "s3": {},
                    "spark": {
                        "cluster_id": "",
                        "clusterKey": "spark.production"
                    },
                    "featureFlags": {
                        "io": "s3"
                    },
                    "envConfig": {
                        "s3": {}
                    }
                }
            }
        },
        "onboardAll": {
            "jobType": "onboard",
            "body": {
                "facadeHost": "${facadeHost}",
                "customerId": "${tokensCustomerId}",
                "logicalDateTime": "${logicalDate}T00:00:00Z",
                "token": "Key ${erc20Token}"
            }
        },
        "onboardAllPolling": {
            "jobType": "endorTaskStatusPolling",
            "body": {
                "facadeHost": "${facadeHost}",
                "customerId": "${tokensCustomerId}",
                "token": "Key ${erc20Token}",
                "taskId": "${taskId}"
            }
        }
    },
    "dependencies": [
        {"origin": "moveBlocksInboxToInProgress", "destination": "parseEthereumTransactions"},
        {"origin": "parseEthereumTransactions", "destination": "parseEthereumBlockHeaders"},
        {"origin": "parseEthereumBlockHeaders", "destination": "moveBlocksInProgressToArchive"},
        {"origin": "parseEthereumBlockHeaders", "destination": "parseEthereumTokenTransactions"},
        {"origin": "moveLogsInboxToInProgress", "destination": "parseEthereumTokenTransactions"},
        {"origin": "moveRatesInboxToInProgress", "destination": "fetchTokenRates"},
        {"origin": "parseEthereumTokenTransactions", "destination": "fetchTokenRates"},
        {"origin": "fetchTokenRates", "destination": "moveRatesInProgressToArchive"},
        {"origin": "parseEthereumTokenTransactions", "destination": "moveLogsInProgressToArchive"},
        {"origin": "fetchTokenRates", "destination": "onboardAll"},
        {"origin": "parseEthereumTransactions", "destination": "onboardAll"},
        {"origin": "parseEthereumTokenTransactions", "destination": "onboardAll"},
        {"origin": "onboardAll", "destination": "onboardAllPolling", "symbols": [{"symbolName": "taskId", "fieldPath": "taskId"}]},
        {"origin": "moveBlocksInProgressToArchive", "destination": "onboardEthereumTransactions"},
        {"origin": "onboardEthereumTransactions", "destination": "onboardEthereumTransactionsPolling", "symbols": [{"symbolName": "taskId", "fieldPath": "taskId"}]}
    ]
}

###